version: 2.1
jobs:
  build:
    docker:
      - image: google/dart-runtime

    working_directory: ~/repo

    steps:
      - checkout
      - run:
        name: Run pub get
        command: pub get
      - run:
        name: tests
        command: |
          pub run test ./test/configuration_test.dart


workflows:
  version: 2.1
  total:
    jobs:
      - build