version: 2

jobs:
  build:
    docker:
      - image: google/dart-runtime

    working_directory: ~/repo

    steps:
      - checkout
      - run:
        name: "Run pub get"
        command: |
          pub get
      - run:
        name: "Run tests"
        command: |
          pub run test ./test/configuration_test.dart


workflows:
  version: 2
  total:
    jobs:
      - build